language: node_js
node_js:
  - "node"
dist: trusty
before_script:
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g firebase-tools
script:
  - npm install
  - ionic platform add browser
  - ionic build browser --prod
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}